### ISSUE TITLE
Engineer report thingy doesn't update to show new limits when switching LC unless you add or remove a part.

### ISSUE THREAD

**Issue by NovemberOrWhatever** [KSP-RO/ProgramsIssueTracker#100]
Seems to be entirely cosmetic, you can still launch if you meet the limits of the new LC, even if the old limits are showing. I've noticed this on Linux, though it's likely not confined to that family of OSs.

**Comment by Gordon-Dry** [comment]
Or just pick the root part (the whole vessel) and let go again, that also resets the engineer report.

**Comment by siimav** [comment]
Fixed
