### ISSUE TITLE
Reputation bonus for early Program completion is insignificant.

### ISSUE THREAD

**Issue by NovemberOrWhatever** [KSP-RO/ProgramsIssueTracker#101]
As it seems to be implemented currently, you only get a handful of reputation for completing a Program early. The amount is insignificant, but enough to make people expect that there should be some sort of direct reward for completing a Program early, when the intent is for the reward to be mostly that you can take a new and better program. I recommend multiplying the rewards by either 10 or 0.

**Comment by ryanc55** [comment]
I played my last save up to Mars boots (knowing full well that this isn't balanced at all).   Later programs were giving enormous amounts, so if it's not 0, it may need to be non-linear.   I'd vote 0 and balance rep just against contracts to make optional contracts more attractive.

**Comment by NovemberOrWhatever** [comment]
Should have been fixed now with a reward increase to the first three programs
