### ISSUE TITLE
Make all RP-1 UI windows Click-Through-Blocked

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/ProgramsIssueTracker#105]
Just to not click any PAW's slider behind it.

**Comment by siimav** [comment]
But which ones aren't?

**Comment by Gordon-Dry** [comment]
I had the Staffing UI in foreground, so in this case that one.

**Comment by siimav** [comment]
Sounds more like a clickthroughblocker issue since it prevents rocket parts from being picked up but not anything in the PAW. Same goes for CTBs own window.
