### ISSUE TITLE
Massive notification spam after 5+ years of siming

### ISSUE THREAD

**Issue by Falki-git** [KSP-RO/ProgramsIssueTracker#106]
I've been siming a long term mission (5+ years) and after years of time warping (July 1981) I started to get massive notification spam (40000+ at the point that KSP crashed). I couldn't see what the notifications were cause they were killing my PC, but Player.log shows "Strategy (XY): This leader's term of service has elapsed. " spammed every line, where XY are various leaders, most of whom I never picked. Also, Maintenance handler spams funding notifications consantly. Not sure where the problem is exactly (bug when leaders are retiring or when reputation gets below 0...?) so I'm attaching some screenshots here. I have a heavily moded install, but this looks like a P&LC issue, so I thought I should report it.

![Leaders retired2_bug](https://user-images.githubusercontent.com/72734856/204934324-f8479de6-ca9c-4e15-b69e-3cc2e7d54b3b.png)
![Leaders retired3_bug](https://user-images.githubusercontent.com/72734856/204934330-8a70cc23-e5e7-4ddc-b443-35bbb2c0cf7c.png)
![Leaders retired4_bug](https://user-images.githubusercontent.com/72734856/204934335-242b9ad0-1677-462e-94ad-cf84d63d8ffa.png)
![Leaders retired5_bug](https://user-images.githubusercontent.com/72734856/204934338-3bf35856-a779-4e5b-9561-44d30d41c49e.png)

[Last 8k lines of the Player.log.txt](https://github.com/KSP-RO/ProgramsIssueTracker/files/10128208/Last.8k.lines.of.the.Player.log.txt)

Full Player.log: https://drive.google.com/file/d/1MFiEef5MxYLCiP4vTBOJleXayZIUYRxy/view?usp=share_link

**Comment by siimav** [comment]
#95 looks related

**Comment by siimav** [comment]
Fixed
