### ISSUE TITLE
Leaders may need rebalancing before more testing can happen

### ISSUE THREAD

**Issue by zephyrspace** [KSP-RO/ProgramsIssueTracker#109]
Aim
=======
While balance has been noted as not currently important, and a new way of accessing leaders will be implemented, we might be running into an issue where players only pick the best/most interesting leaders and as such we might not get testing data for less popular leaders. With this in mind I'm going to try and do a rough balance pass to make attempt to make leaders equally appealing. 

I'm posting the proposed changes below as an RFC before I start implementing

Administrators
============
The total list of effects that the admin leads can currently access are as follow: 
* +- rep from all sources
* +- confidence from all sources
* +- salaries for all employee types
* (+)- program funding
* +(-)costs to remove leaders
* +(-)eff gain
* +(-)integration speed
* +(-) science from all sources
* +(-) reputation decay
Note: symbols in parenthesis are effects that don't currently exist but could very easily. For example, Von Braun has "Difficult", currently reduces confidence from science, but could easily increase reputation decay (an effect that doesn't currently exist, and possibly suits the whole, "hard to get along with" idea better)

Von Braun
--------------
* positive: The difference between Political Savvy and Charismatic actually does a lot to educate players about the difference between the two currencies
* negative: The difficult modifier disincentivising science (with -confidence from science) feels weird with his CD trait of Technical Genius
* recommendation: possible buff the percentages to 12% each and shift difficult to a rep decay trait, incentivising launching faster and making Von Braun the "Contract Rewards admin"

Korolev
----------
* negative: Hero of the Soviet union is 10% on Korolev and only 5% on glushko, and while I guess he got two of them, it's still a bit weird from a game pov
* positive: salary reduction is a neat trait though it does outclass glushko
* positive: funds decrease is a good thing because it kind of forces you to go big, so that the salary discounts outweigh the funds decrease
* recommendation: move the reputation gain +5% to match glushko, and possibly shift the salary reduction to -12% to make him the "Go Big admin"

Glushko
------------
* neutral: current hero of the soviet union buff is outclassed by korolev but this is fixed by the other recommendation
* negative: engine design genius, being a -10% discount on researchers makes this a specialisation of the korolev trait but with it being the same amount as korolev it means it can only be as good as korolev if 100% of your employees are researchers. 
* negative: Turned in Korolev: increases the funds cost to remove leaders, who don't need funds to remove
* recommendation: Possibly having him reducing science costs for the orbital rocketry line (or all tech if feeling spicy) might be a different qualitative change and make him an RnD focused admin in a different way. Turned in Korolev should just be fixed by changing the currency to reputation

* implementation notes: turns out i forgot or didn't know that you can't discount specific tech nodes. So currently i've just bumped the researcher discount to 15%.

Chelomey
--------------
* positive: speed increase to LC efficiency gain is an interesting new trait for admins
* neutral: confidence reduction is a good mechanic but tends to only shave 100/200 confidence off the first few new programs (so like 1 or two launches at best), this might be more impactful in the later game where confidence is currently less available and costs are higher
* negative: Rep reduction from contracts might be too generic/ineffectual of a debuff
* recommendation: move the confidence reduction up to +15%, and the reputation nerf up to 7% to make him a bit more of a conscious choice towards "long term, condfidence over reputation, program over contract" play

Sarabhai
-------------
* positive: A high confidence from science percentage makes the leaders position clear
* negative: the bonus integration speed from instruments and avionics are really more of a chief designer/chief scientist perk
* positive: The increased tooling costs mean that you're forced to use "older" LVs/LVs that don't really need tooling (like solids based ones)
* recommendation: maybe have him discount the avionics and instruments unlock, that or shuffle the ISRO leaders around to better match gameplay concerns instead of historical titles

Dhawan
------------
* neutral: plus transmitted science is a unique perk for a admin but it might not actually be suited for this role, also allows you to stack +25% science with van allen which might be a problem
* positive: reputation decay prevention is a decent minor trait that allows players to play a lower launch frequency (though I'd actually have to run the numbers to see how much rep this actually saves per year)
* negative: funds reduction bumps into korolevs space but without the salary reduction it doesn't really have the same "go big" effect
* negative: Sarabhai and Dhawan have obvious synergy but can't actually be selected together (historically accurate as they were successive directors of ISRO but annoying from a gameplay perspective)
* recommendation: probably shuffle the isro leaders, but since I added them I can't really provide a new perspective on this

**Comment by zephyrspace** [comment]
Chief Designers
=============
By far the broadest and most impactful section of leaders

Von Braun
---------------
* negative: the only generic +research speed perk that i can find and it's not as powerful as the generic integration speed one from korolev (not to mention his OKB), this has the effect of making RnD speed builds uninteresting (at least from a straight numerical standpoint, +5% generic + whatever you get towards specific techs is just not as interesting as, +25% generic integration speed + other generic integration speed perks)
* mixed: saturn v visionary and cautious have the effect of sort of canceling out in terms of speed, possibly spending two traits on one thing (with both being less important as a result)
* recommendation: increase the research speed buff to 10% as this is basically the main benefit of CD Von Braun. Also change Saturn V visionary to a +5% to hydrolox so it stops fighting the integration nerf and to make Von Braun the RnD mirror of korolev (with an early generic rnd buff and a later specialized rnd buff). And shift the integration speed nerf to 7%

Sergei Korolev
---------------------
* mixed: created the r7 lv is a very strong integration bonus, which also fits korolev, but it's also so strong it makes some of the other leaders irrelevant
* positive: put first man in space is a good way of keeping korolev relevant as programs shift over to crewed
* negative: -5% to materials node might be too easily compensated for/ignored
* recommended: keep as is but buff the other CD's to compensate. (possibly nerf the research speed penalty towards a -7% to be a bit more obvious and impactful)

Valentine Glushko
---------------------------
* positive: the perks are all really clear as to the play style they're supposed to play into
* recommendation: possibly shift the percentages to a +12/+7 split depending on if glushko is supposed to be more early game (+12 to EaOR, +7 to SC) or late game (+7 to EaOR, +12 to SC). Otherwise keep as is unless others feel he needs a buff?

Mikhail Yangel
---------------------
* negative: literally a worse korolev as the integration speed bonus isn't any better and the tech speed nerf is worse as it applies to all techs
* note: he's noted as a hypergolics pioneer but doesn't have the hypergolics pioneer trait (probably fine for avoiding mechanical redundancy but still fun to note)
* recommendation: lean into the funds reduction by making it a -15% and maybe rename it "Practiced Efficiency" unless "Works for Us" is something he was noted for saying

Charlie Bossart
----------------------
* negative: he only has two traits
* recommendation: Add either "The Centaur Upper stage": +10% to hydrolox research speed or "Structures Expert": +10% to Mat Sci research speed

Max Faget
----------------
* negative: these are very late tech nodes (which might be fine if he's only available late), with quite low percentages (probably only shaving a month off rnd) 
* recommendation: Shift capsule designer to a +10% buff to Command Module research speed, and shift the second one away from EDL and towards crewed vehicle integration speed? (+10%)

Mary Sherman Morgan
----------------------------------
* negative: only has two positives
* negative: whimsical is such a small nerf to confidence it might as well not matter
* negative: while not outclassed by korolev, she doesn't have possible +15% korolev gets when integrating crewed craft
* recommendation: One buff from an "Expert Chemist" buff which would increase integration speed of Turbopump Engines (would like hypergolic engines but idk if theres a tag for that?). In the future having it increase test flight reliability or even increase hypergolic engine isp (for those people who like playing on arcade mode idk)? Also changing the Whimsical trait to "Dismissed as Whimsical" and shifted to a -5% would be more appropriate for someone who was the sole female engineer (without a college degree) at rocketdyne in the 50s

Arthur Valentine Cleaver
-----------------------------------
* negative: 5% to vessel rollout is very different to the +15% that the other integration specialists can pull (+10% to kerolox/oxide +5% rollout isn't the same as +10% overall +5% crewed)
* recommendation: change the +5% to rollout to, +5% to integration/rollout/rollback. meaning that players can get the 15% speed equivalent to korolev if they build kerolox/oxide rockets

Abdul Kalam
------------------
* negative: the +15% to tooling costs (which can't be done over time and now represent one of the biggest gating events in PaLC) is a large penalty for what isn't actually that big a buff
* negative: with the clear lines on what rep/confidence mean now, kalam's trait is probably best defined as rep? (idk sources were unclear about his personal appeal vs political power)
* recommendation: changed beloved to a +10% to rep from contracts, and change home grown tech to a +10% increase in costs as well.

Notes
---------
With that the second longest category is done. I'll probably move to contractors next? Hopefully categorizing the behavior of entire companies should be easier than single people. Also I would definitely like a second pair of eyes on Kalam at a bare minimum because I was the person who added him (and the other ISRO leaders) and I probably have my own idea about how things should be that would benefit from others perspectives

**Comment by zephyrspace** [comment]
Flight Directors
=============

Chris Kraft
----------------
* negative: I'm not sure how much sense it makes to have integration and rollout be two separate traits on a leader when there are a lot of leaders with them combined?
* recommendation: merge the two mission control traits into one, and add one called lasting legacy which increases LC efficiency gain by +5%

Gene Kranz
-----------------
* mixed: failure is not an option feels like a trait that should boost confidence not reputation? but idk I'm nitpicking
* recommendation: keep as is

Homer Hickam
----------------------
* mixed: this is probably personal preference but having different traits have the same name feels weird but idk if this is just how we want this to be
* recommendation: ask november about going over the trait names?

Vladimir Barmin
------------------------
* mixed: see above about traits
* mixed: it feels weird that a trait called "no planes at baikonur" only makes rocket planes (and airlaunched rocket planes at that) cost more
* recommendation: rename the "no planes at baikonur" trait or change it to increased SPH integration/rollout times?

Chief of the Astronaut Office
=======================
A general note is that this area may or may not overlap with flight directors? Maybe a more generic name could be used that encompasses the two: "Crewed Operations"? This might also put a similar number of leaders in each category, lower the overall number of categories/leave space open for a new category (ROPolitics wen?). All recommendations are made with the assumption that all categories currently stay the same.

Deke Slayton
-------------------
* negative: the two chief astronaut pioneer traits feel like they should be merged into one like some of the combined rollout, integration and rollback costs
* recommendation: assuming that was possible, merge those traits and add a new one called "crewed flight is prestigious" that gives +5% to reputation from contracts? (is it possible to target individual contract requirements, cause +15% rep from crewed contracts would definitely be a cool thing to add?)

Yuri Gagarin
------------------
* recommendation, same as deke but with confidence (including the +15% to crewed contracts if/when that becomes a thing)

**Comment by zephyrspace** [comment]
Chief Scientist
============

Betty Love
---------------
* negative: feels like she has two alright abilities instead of any good ones, especially with that real penalty as cockpits tend to be one of the most expensive parts of a plane
* recommendation: to check if leaders without a clear specialty but with lots of decent value are viable, increase both percentages on x-1 pioneer by 3, so (+8% to flight tech, and -13% to decrease on air launch costs)

Yvonne Brill
-----------------
* negative: she only has one (pretty midgame and limited) positive
* recommendation: lean into the hyperfocused aspect by adding another trait also called "Hydrazine Resistojet Requires Little Innovation" (if we're going for that irony factor in trait names?) that discounts the science needed to unlock RCS tech nodes by 10%

Katherine Johnson
---------------------------
* positive: seems like a leader with a clear role and aim, and a historically relevant downside
* recommendations: none, possibly bump one of the two positives up to 10%? Probably not the integration speed one cause that's probably too good with all the other integration specialists in chief designer and contractor. So if it turns out players aren't picking her then try buffing the avionics research speed?

Jack Parsons
------------------
* note: haven't made a run that relied primarily relied on solids (mostly because the V2 or the aerobee is basically required to progress through the early game in a sane manner) so my ideas are mostly theoretical here
* mixed: owing to solids nodes being so cheap already accelerating them by percentage amounts shaves off less absolute time than other focuses, making percentages at least in theory less powerful than they otherwise would be
* recommendation: this first one is more of a wishlist but the ability to specify absolute values in leaders might be fun (i.e. discount the solids tech nodes costs by -1? So its an early game kick but tails off hard?). Otherwise just bump the research percentage by 2% ish to compensate
 
Theodore von Karman
--------------------------------
* negative: the kind of broad bonuses to research (solids and flight in particular) and negatives and decrease to integration times means he kind of fills the same roles as von braun (good for stacking i guess?), betty love (currently at the same rate) and jack parsons (for solids but at a lower rate)
* recommendation: maybe keep him as a low impact generalist? to see how favorably those are? But is it possible to only decrease the speed of crewed VABs? Cause having crew safety concerns around uncrewed rockets is a bit weird? Otherwise: just bump them up to +6% each for the people taking us-bee-plane starts?

James van Allen
------------------------
* positive: Science gained from transmission and recovery is a powerful, interesting and rare trait
* mixed: it occasionally feels like with occasional player complaints about low science numbers that +science might be too strong a trait to have in general? 
* mixed: the science trumps all trait might be better suited to just making the instruments more expensive? though it is a strong negative that currently exists for the purpose of balancing out the strength of the +science trait
* recommendation: I will possibly move some of the ISRO leaders around so you can't stack van allen and sarabhai at the same time for +25% science. if sacrificing historical placements for gameplay isn't deemed acceptable then reducing the increased science from one of them (probably sarabhai) or refocusing one of them (probably van allen?) towards their other trait (in van allens case research speed bonuses)

Mikhail Gurevich
------------------------
* negative: only has two bonuses right now
* recommendation: add a trait for "Acclaimed Bureau Leader" that discounts reasearcher salaries in the same way Admin Glushko's does

Nambi Narayanan
--------------------------
* negative: the primary motiviation for possibly repositioning the ISRO leaders, the skill set that Narayanan brings to the table more more reflects CD glushko than the other scientists
* recommendation: position the ISRO leaders so it goes (admin: Dhawan, CD: Narayanan, FD: Kalam, CS: Sarabhai), which fixes "the Van Allen + Sarabhai stacking might be too strong" problem, the "Dhawan and Sarabhai synergise well but cant stack" and the "you can't really take all the ISRO leaders at once if you're doing an ISRO run" problem

**Comment by zephyrspace** [comment]
Contractors
==========
I'm trying something a bit different which is change the position contractors play from "just another leader" to an actual external contractor i.e. you bring them in to help on one specific thing and they come with their own issues. The aim is to make the contractors net neutral so that if you don't have a firm idea for your program, you don't pick one. This has the outcome of mentally separating leaders and contractors in the players head (hopefully) and allowing more customisation without the player feeling like they "need" contractors for optimal play which helps in current historical runs for nations that don't have contractors, as well as runs that play against their nations historical aims for one reason or another.

With this in mind, I'm proposing a system of taking a contractor as main contractor, which nets you a strong positive and strong negative, or an auxiliary (sub?) contractor, which nets you a weaker positive in exchange for a currency cost (1,2 or 3% of program funds, or a -5,10,15% of all contract rewards?). Also to increase the playstyle differences I'm making the US contractors mainly RnD focused with a VAB/SPH subcontractor, while Soviets get a VAB focused main contractor with an RnD focused subcontractor

Douglas Aircraft Company
--------------------------------------
* main contractor:
  * +10% to materials node tech research speed
  * -10% to early and orbital rocketry
* sub contractor:
  * Thor and S-IVb tanks: -5% integration speed to tanks (new)
  * -5% program funds


Bell Aircraft Company
--------------------------------
* main contractor:
  * +10% to Flight tech research
  * -10% to Avionics tech research
* sub contractor:
  * -15% decrease funds to the cost of airlaunch (moved and buffed)
  * -2% program funds

Rocketdyne
-----------------
* main contractor
  * +10% to Hydrolox Engine tech research speed
  * -10% to Staged Combustion
* sub contractor:
  * +5% to Early and Orbital Rocket Engine tech research speed
  * -2% to program funds

Atomic Energy Commission
----------------------------------------
* main contractor
  * +5% Nuclear Rocket Engine tech research speed
  * +10% Speed increase of Daily Reputation Decline
* sub contractor:
  * +5% to integration speed of nuclear parts
  * -3% program funds

Aerojet
----------
* main contractor
  * +10% to integration speed of pressure fed engines
  * -10% to integration speed of Human Rated vehicles
* sub contractor
  * +5% to Solid Rocket Engine tech research speed
  * -1% program funds (1 less than rocketdyne's liquid buff to compensate for solid nodes being cheaper and so the same percentage shaves off fewer days)

JPL
----
* main contractor:
  * +10% to avionics and electronics research speed
  * -10% funds increase to the cost of vessel purchase and launch
* sub contractor:
  * +5% to integration speed of instruments
  * -1% program funds  (instruments don't tend to be that expensive so just discounting them probably shouldn't cost much)

McDonnell Aircraft Corporation
----------------------------------------------
* main contractor:
  * +10% to command module tech research speed
  * -5% to integration speed of Human Rated vehicles
* sub contractor:
  * Aircraft Designers: +5% to cockpit integration
  * -2% program funds

OKB-1 Korolev
---------------------
* main contractor: 
  * +10% speed increase to all craft integration speed
  * -10% research speed for all techs
* sub contractor:
  * Manned Spaceflight Visionary: +5% to capsules research speed
  * -10% of all contract rewards

Ilyushin Design Bureau
----------------------------------
* main contractor:
  * +10% to integration speed of Cockpit parts
  * -10% to flight research speed
* Ilyushin Design Bureau
  * No Need to Innovate: -5% researcher salaries (ngl I might be warming up to these positive/negative buffs with the same name jokes)
  * +5% of all contract rewards

OKB-52 Chelomey
---------------------------
* main contractor:
  * +10% increase to engineer efficiency gain for LCs
  * +10% funds increase to cost of Hiring Employees
* sub contractor:
  * +5% to Stations tech research speed
  * -5% of all contract rewards (might need to be buffed/nerfed based on how powerful stations end up being)

OKB-456 Glushko
--------------------------
* main contractor:
  * +10% to integration speed of Turbopump Engine Parts
  * -10% to Hydrolox Engines
* sub contractor:
  * +5% to Staged Rocket Engine tech research speed
  * -10% of all contract rewards

OKB-276 Kuznetsov
----------------------------
* main contractor:
  * +10% to Staged Rocket Engines tech research speed
  * -10% to early and orbital rocket engines tech research speed
* sub contractor:
  * +10% to Staged rocket Engine integration speed (idk if i can target SC engines like I can turbopump engines though)
  * -10% of all contract rewards

**Comment by NovemberOrWhatever** [comment]
I think all this has been implemented by now, but you can reopen if that's not the case
