### ISSUE TITLE
Crewed Lunar Program Requirements are weird

### ISSUE THREAD

**Issue by Teykn** [KSP-RO/ProgramsIssueTracker#110]
The Crewed Lunar program currently only requires that the Crewed Orbit program be completed. However, the Crewed Lunar Landing contract requires two contracts be completed which are from the Uncrewed Lunar program (Uncrewed lunar orbit and uncrewed lunar landing).

Would suggest either removing the contract requirements, if crewed orbit is intended to be the only required program, or removing the contract requirements and adding a program requirement, if uncrewed lunar is intended to be a prerequisite

**Comment by NovemberOrWhatever** [comment]
I removed that requirement a while ago but forgot to close this issue. You shouldn't be able to softlock that way now.
