### ISSUE TITLE
Downrange contracts are uncancellable - soft locks when launch fail for whatever reason

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#111]
There is problem with contract exclusivity. Currently when selecting contract all other contracts are gone (early ones at least including early satellites) so selecting downrange contract even just before launch and having rocket fail locks you with any progress until you fulfill that program since it is uncancellable. Oter problem is that you cannot effectively work on two different rocket groups sending for example bio / film payloads on one type and downrange on other as contracts are exclusive. 

Other problem is that selecting first satelite contract also.. removes everything else from previous contract options so again soft lok or penalty for cancelling depending on one.

![obraz](https://user-images.githubusercontent.com/38114978/210213453-7c5f336f-f5ab-4ca1-b560-02cac8c98d97.png)

Shouldn't we define more strict contract launch profiles, or requirements instead of forcing single contract option ? We could define that bio payload cannot go higher than x, or not further that Y , also recovering is far different requirement that downrange. We could define that you cannot exceed certain G limits or simply not having sounding payload/ other payload onboard etc if we are so scared of hacky people ;)

**Comment by siimav** [comment]
All contracts are cancellable now
