### ISSUE TITLE
Trimming the decision tree: Gate Leaders and Programs

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/ProgramsIssueTracker#113]
The current gameplay loop for starting a P&LC career is pretty poor, as discussed previously on discord. Good game design practice encourages that you limit the options to a new player, and open them up as time goes by (the "Decision tree"). P&LC does not do this, instead encouraging the player to open the admin building as one of their first actions, where they are presented with hundreds of possible combinations of leaders and administrators, as well as several possible programs. My personal experience, as well as streams from other players, show that even an experienced player can spend upwards of an hour in the admin building before even building their first craft.

However, these ultimately have little immediate effect on the player. The start of a career sees small, basic designs and very limited research opportunities, meaning the bonuses and maluses given by leader selection has very little effect on gameplay. 

Similarly, the programs offered are all ultimately gated by the first launch contract (although it is easily possible to complete the "Karman Line", or with some skill the "Break the Sound Barrier" contracts at the same time). Still, there are only two intended gameplay paths for the player's first launch, either a standard sounding rocket or a supersonic X-plane.

In the name of trimming the decision tree, and putting the player in the VAB/SPH as soon as possible, I suggest the following:

### Gate leader slots 
Most leader bonuses and maluses have very little effect on the players first craft, or first research project, leaving only a few "optimal" choices. Instead, placeholder leaders should be placed in slots at the start of the game, or the slots simply blocked off completely. Appointing leaders can wait until the player has consequential decisions to make, unlocking slots either upon the completion of certain programs, or reaching certain points in the tech tree.

### Starting program
Rather than the current 3 starting programs (which may be a trap to new players, completing the X-planes contract requires some skill in aircraft design, and taking the Early Rocket and Suborbital programs at the same time can actually result in a time crunch even for experienced players), I propose a simple starting program, which gates all other programs, and can be completed by doing the "First Launch" contract, as well as either the "Karman Line" or "Supersonic Flight" contract. It should have a very long deadline but a very low funding level, just enough to offset maintenance of an early career. Hopefully, it will serve multiple purposes.

- First, it will simplify the game start, allowing the player to completely forgo the admin building for the first launch or two (trimming the decision tree)
- Second, it will provide a safe tutorial to teach the player about meeting program goals and completing programs. The long duration and baseline income should provide enough cushion to let a new player get their bearings and perform a few launches, before finishing it and moving on to more lucrative programs.
- Finally, it will act as a "plane gate". Constructing planes in stock KSP is challenge enough for many players, dealing with proc wings, FAR, altitude limits, and underpowered early engines of RP-1 can prove quite difficult. Offering the relatively easy "Karman Line" contract next to the much more difficult (with starting parts) "Sound Barrier" contract will allow players to "test the waters" of plane design in RP-1 before commiting to an aircraft-focused program. A player that might accept the X-planes program immediately only to find their plane-building skills are lacking will instead fail to complete the "Sound Barrier" contract and be forced to do the "Karman Line" contract instead, while still in the safe space of the starting program.

**Comment by siimav** [comment]
Leader gating is available here: https://github.com/KSP-RO/RP-0/pull/1914

**Comment by NathanKell** [comment]
If taking both rocketry programs results in a time crunch, that sounds like a balance problem for those programs?

**Comment by NathanKell** [comment]
Leaders gated.
