### ISSUE TITLE
Problem with contract "Orbital Test Flight (Animal Crew)"

### ISSUE THREAD

**Issue by jgalak** [KSP-RO/ProgramsIssueTracker#114]
Contract specifies that a "tourist" test animal needs to be in the crew capsule.  Tourists appear in the astronaut complex and can be placed in the capsule in the VAB, but when the vehicle is launched, KCT's "Select Crew" screen says "No trained crew found for this cockpit or capsule."  Likewise, in flight, no one appears in the vessel and the contracts window in-flight doesn't show checkmark for "Animal Crew"

Screenshots in the Discord, here: https://discord.com/channels/319857228905447436/987914369318944788/1079226808882434111

**Comment by Sauge** [comment]
I have exactly the same issue

**Comment by siimav** [comment]
Fixed
