### ISSUE TITLE
X-15 Mission Training Not Registered

### ISSUE THREAD

**Issue by yigitemres** [KSP-RO/ProgramsIssueTracker#115]
Reloading save or load save from main menu and doing the training again doesn't work. My P&LC is from commit KSP-RO/RP-0@7099b22.

Bug is probably from this:
After finishing  training, `training mission` popup about retirement is not activated and we cannot click `Acknowledge`. Because of this, training status is not registered on the pilot.

**Comment by siimav** [comment]
> doing the training again doesn't work

What exactly do you mean by this part? You can start a new mission training for the same naut? Can't start training all for them? Mission training no longer exists for the pod?
The retirement popup will also not appear when the naut has already reached the max retirement extension.

**Comment by yigitemres** [comment]
I don't know this exist in current build (I start new save every time for every release in order to test) but this was how it goes:

1. Start the training.
2. Fast forward in time in order to complete the training.
3. Training completes but there is no `Acknowledge` prompt popup (BTW, I suspect this is the main cause. The `Acknowledge` button itself probably register the mission to astronauts. Just check the if mission registration happens before or after the popup itself).
4. Can't start the mission because training doesn't registered (I inspect the astronauts and see no `X-15 Mission`).
5. I can start the training again for the same astronaut (with or without the restarting game completely) the `training` is added to queue but everything is reset to step no 2. 

> The retirement popup will also not appear when the naut has already reached the max retirement extension.

I'm not sure about this part part If I remember correctly I don't reach the max retirement extension (🤏 🧂).

**Comment by siimav** [comment]
Unfortunately I can't replicate this issue with X-15 mission training. 
One potential problem that I could see happening is with proficiency training if the part gets researched before the training completes. Proficiency courses aren't created for parts that are researched but not yet purchased. This would probably cause the prof course to not get registered correctly.

**Comment by yigitemres** [comment]
It's all good. Thanks for your efforts and have a nice day! 🥂
