### ISSUE TITLE
mars surface exploration program stuck

### ISSUE THREAD

**Issue by Tsits11** [KSP-RO/ProgramsIssueTracker#116]
I've accepted the mars surface exploration program and I'm far enough on science tech (done moon landing) 
After completing the mars atmospheric probe contract the program gets stuck and won't provide me with any more contracts.
In the complete available contracts list it shows as needing programm UNMET

however it still provides me with the mars orbital probe contract from the previous Inner Solar System probes Program... I think it got messed up

**Comment by siimav** [comment]
Need save file or exact steps to recreate the issue.

**Comment by Sauge** [comment]
@siimav  I have the same issue I attaching my save file 
[persistent.zip](https://github.com/KSP-RO/ProgramsIssueTracker/files/11303803/persistent.zip)

**Comment by siimav** [comment]
Should be fixed now.
