### ISSUE TITLE
Upgrading LC while vessel is rolling out changes rollout time to infinity

### ISSUE THREAD

**Issue by dcwhitworth** [KSP-RO/ProgramsIssueTracker#118]
Upgrading a launch complex while a vessel was rolling out changed the roll out / back time to infinity.
<img width="339" alt="Rollout Issue" src="https://user-images.githubusercontent.com/130874917/232258334-8b379979-eae3-4c90-9f37-8904ac2df69b.png">

**Comment by Sauge** [comment]
did you reassign engineers back to it after the upgrade?

**Comment by dcwhitworth** [comment]
<facepalm> Of course that's the problem. Sorry I logged this at the end of a long day after many frustrations with the game, caused by my incompetence, not the game itself. I should have recognised the pattern !
