### ISSUE TITLE
'Modify' LC button disappears

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#12]
minor but confusing:

In space center view, open kct window, click Staff button: Modify button is hidden (expected)
Click the VAB: after scene switch, Staff window has closed, but Modify button is still hidden for no obvious reason

Another scene switch fixes it.

Originally saw the missing button in the space center scene, but haven't actually been able to repro that

**Comment by NathanKell** [comment]
*$(*^# static KCT fields.

**Comment by NathanKell** [comment]
Nope, this is because modify doesn't appear in the editor. Not really sure why I did that, so I'm going to reenable it. We'll see what breaks.
