### ISSUE TITLE
It is super unclear how to select animal as crew (tourists)

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#120]
I just learned for the first time that one can select crew from this window : 
![obraz](https://user-images.githubusercontent.com/38114978/232299150-33897aad-392c-486b-8b20-f7737cc17018.png)
It should be added to first crewed mission that you need to click remove and then add to select crew.

And it does not honor vab selection too - nice to note to reduce confusion :)

**Comment by siimav** [comment]
I don't really understand how you're learning about that window only now.
It would probably make sense to assign the test animal as default crew whenever one is available.

**Comment by byt3c** [comment]
Usually i manged crew by having only specific crew members available by training for missions. I was not aware that one can select particular crew member here.

**Comment by siimav** [comment]
Actually if you had the crew training feature enabled then a test animal would've gotten autoassigned to that slot. Highly unlikely you would've had a naut with proficiency + mission training just waiting around.
