### ISSUE TITLE
while doing animal mission there is contract configuration bug

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#121]
there are contradicting requirements - have a space for a crew and animal on board and uncrewed vessel...
![obraz](https://user-images.githubusercontent.com/38114978/232301029-354807cb-159c-42c7-8a29-57b9cec0ac0a.png)
and yes i have felicity the cat as crewmember :D

**Comment by byt3c** [comment]
and during staging within atmosphere it switched to correct conditions. 
![obraz](https://user-images.githubusercontent.com/38114978/232305153-ce2f4e37-35a5-48cc-88e0-f2c1bd440752.png)
unfortunately it does not detect the animal.

**Comment by byt3c** [comment]
![obraz](https://user-images.githubusercontent.com/38114978/232325279-04cc12d3-bce1-4244-8180-96e7451ff163.png)
this time i could not select any animal, but i had tourist with Kerman name on second animal mission. Strangely enough all markers are checked  correctly.

**Comment by byt3c** [comment]
after 140km altitude and stage i have this : 
![obraz](https://user-images.githubusercontent.com/38114978/232325577-89059086-d53e-43af-92ab-9da5e7527472.png)

**Comment by byt3c** [comment]
after completing orbit requirements all checkmarks are now ok : 
![obraz](https://user-images.githubusercontent.com/38114978/232325713-feaa30a1-2bfa-4bc1-bb3c-b67ecab8724b.png)

**Comment by byt3c** [comment]
Apparently sth went wrong again - maybe exploding/ burning other components triggered it 
![obraz](https://user-images.githubusercontent.com/38114978/232326229-705d72a0-4415-4902-a280-7676f0340e3a.png)

**Comment by siimav** [comment]
Did you switch vessels at any point during the flight or did the vessel that eventually landed back on the ground stay active all the time?
I can see that the CC parameter updates the status on only the active vessel which is a bit odd but not sure if it's an actual issue.

**Comment by byt3c** [comment]
I cannot remember unfortunately. But it is entirely possible that i de-orbited booster stage so quick craft switch might happened.
As far as i remember since separation , during making manevuers and tracking orbit craft was never switched.

**Comment by siimav** [comment]
Latest CC got some changes to crew check logic.

**Comment by NathanKell** [comment]
Closing this on assumption the issues around these contracts are fixed now.
