### ISSUE TITLE
Orbital and suborbital crewed contracts are avaialble at the same time

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#122]
There is warning that any picked suborbital contract will be failed, but contracts are still there. There is indeed actual failure when selecting a suborbital contract afterwards, but returning to a saved game without remembering failure warning from orbital contract might be frustrating. So suborbital contracts should be removed after orbital one is accepted.

**Comment by siimav** [comment]
Honestly not sure if it's intended or not. The upside of having all of them available despite the conflicts is that MC would show upcoming contracts as well.
Either way, there's a prompt now: https://github.com/KSP-RO/ContractConfigurator/commit/024354874abc6dd345d2462bce91ad66c12967b3

**Comment by NathanKell** [comment]
Intended.
