### ISSUE TITLE
KCT revert always goes to VAB even for planes

### ISSUE THREAD

**Issue by ec429** [KSP-RO/ProgramsIssueTracker#124]
Steps to reproduce:

1. go to SPH
2. build a plane
3. start a sim
4. open KCT menu
5. click "Revert to editor"

Results:
Now in the **VAB** with the vessel.

Expected results:
Back in the SPH with the vessel.

Workaround:
Using the Revert button from the KSP pause menu works as intended and returns to the correct (SPH) editor.

**Comment by Dracolupus314** [comment]
Did you confirm that you are set to the hanger on the KCT screen in the hanger, not one of the pad LCs?

**Comment by NathanKell** [comment]
Just pushed a speculative fix. Try now? If that fixes it, we 100% have a bug with BLV.Type getting changed after BLV creation.

**Comment by ec429** [comment]
Nope, still broken.

**Comment by NathanKell** [comment]
Turns out this was because the LaunchedVessel is nuked as part of flight scene setup, so you can't expect to access which facility it was built in. Now use stock behavior for figuring out which scene to revert to.
