### ISSUE TITLE
Engineer lost when dismantle launch pad

### ISSUE THREAD

**Issue by confessus** [KSP-RO/ProgramsIssueTracker#125]
Commits on May 13, 2023
https://github.com/KSP-RO/RP-0/commit/e249ef4d9c393110732e8c9f5180174adefedf6e

If you have affected engineer to a Launchpad and you dismantle it, you can not reaffect them after.
- Affet engineer to a launch pad (90) 
- Dismantled it. 
- Total engineer still to 200, but no free engineer

**Comment by siimav** [comment]
I think you meant "Launch Complex" instead of "Launchpad".
Tried this on my own dev install and after dismantling the 17 engineers in that LC are now reflected in the Unassigned column.

**Comment by confessus** [comment]
I will try to reproduce and give better description of needed step ( I quickly reload after the bug)

**Comment by confessus** [comment]
I try again to reproduce without success, I close the issue

**Comment by confessus** [comment]
I try again to reproduce without success, I close the issue
