### ISSUE TITLE
Engine configuration seem to be lock (can be linked to a RP0 version updated)

### ISSUE THREAD

**Issue by confessus** [KSP-RO/ProgramsIssueTracker#126]
Current configuration : https://github.com/KSP-RO/RP-0/commit/3ee7c90d56a92afa00f08447ba4cb79890aca62b

Initial version before update : https://github.com/KSP-RO/RP-0/commit/e249ef4d9c393110732e8c9f5180174adefedf6e

Even with money it is not possible to unlock engine option in VAB (see screen shot) 
Notion Nan after subsidies

![bug](https://github.com/KSP-RO/ProgramsIssueTracker/assets/1291419/367cb912-70a6-4223-9403-9291eda7c862)

**Comment by siimav** [comment]
> Initial version before update : https://github.com/KSP-RO/RP-0/commit/e249ef4d9c393110732e8c9f5180174adefedf6e

And by this you mean that you started your career with this particular version of NotBudgets branch?

**Comment by confessus** [comment]
Yes I start the carrier with https://github.com/KSP-RO/RP-0/commit/e249ef4d9c393110732e8c9f5180174adefedf6e 
And update to https://github.com/KSP-RO/RP-0/commit/3ee7c90d56a92afa00f08447ba4cb79890aca62b 

Sometime after when I try to create a new rocket, the upgrade was locked .

I'm not sure it is directly linked to this version change, because I some time, and I'm not sure that it's directly linked. If you think so, just clause the bug, I will create a new carreer in the futur. 

Thanks for your work, it's great, I hope such feedback help, if not tell me.

**Comment by siimav** [comment]
Should be fixed by https://github.com/KSP-RO/RP-0/commit/150013735dbb1fefccb152d88e41ec3e5c033ba6

**Comment by confessus** [comment]
Than,ks a lots
