### ISSUE TITLE
First Science Orbiter contract is basically useless now

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/ProgramsIssueTracker#13]
We need to either make this one the prereq for the ones that come after it, or remove it entirely.

**Comment by NathanKell** [comment]
We only ever added it to deal with the cancerous nature of Advances. Now that we have programs it can go away.

**Comment by leudaimon** [comment]
Maybe we should tighten the requirements on FO a bit then?

**Comment by NathanKell** [comment]
Agree. Probably should just use the FSO requirements (excepting the experiment).

**Comment by lpgagnon** [comment]
this would bring back the original problem that led to the FO/FSO split, that it's weird if there's no reward at all for "getting into _some_ orbit, no matter how lame"

or, to put it another way: you require FO to hit 1500km Ap, you screw over sputnik

**Comment by NathanKell** [comment]
I'm fine with 200 x 800 (Sputnik 1 was 215x939). But I definitely think we need a perigee higher than 140, and an apogee higher than 300.

**Comment by Teykn** [comment]
Would optional parameters work to resolve the issue? E.g. Reach orbit of Pe >= 200km, Ap >= 300km, with optional parameter of Ap >= 1500km?

**Comment by NathanKell** [comment]
Yeah, that makes sense!

**Comment by siimav** [comment]
The problem with optional parameters is that if you complete the minimal contract requirement but fall short of the optional ones then the contract will complete and you won't get a second chance at doing the optionals.

**Comment by Teykn** [comment]
Couldn't that safely be resolved by setting the duration in the optional parameter to be less than the main parameter, so that the optional parameter is completed first? So, 2 minutes to satisfy the optional orbit and 5 minutes to satisfy the main orbit?

**Comment by siimav** [comment]
Sure but if the vessel falls short of the optional requirements because of TF failure or mistakes in the flight profile then you might want to launch another rocket.

**Comment by Teykn** [comment]
Did not think about that, yeah that would be an issue. 
Only other reasonable solution I can think of is combining First Solar and First Sci, but would that be historically accurate to the satellites those contracts were meant to represent?  

Ok, this idea might not be good. Explorer 1 did not have any solar panels but Sputnik 3 did

**Comment by lpgagnon** [comment]
> if you complete the minimal contract requirement but fall short of the optional ones then the contract will complete and you won't get a second chance at doing the optio

That seems ok to me. 
- Send your very first satellite to 1500km, world is very impressed, have some bonus rep.
- Send your first satellite to 200km, your second to 1500km, world is less impressed, no bonus rep for you

**Comment by Starcatcher2009** [comment]
I personally think that the requirements should instead be "spend this amount of delta v or above, and have Pe/Ap above 140km"
Sputnik and Explorers were basically cases of "Your Periapsis and You" shenanigans, and no one really stops you from making a longer burn-time rocket.

**Comment by Starcatcher2009** [comment]
(This is a response to NK’s opinion about the FO requirements)

**Comment by ajvaughan** [comment]
> The problem with optional parameters is that if you complete the minimal contract requirement but fall short of the optional ones then the contract will complete and you won't get a second chance at doing the optionals.

How much would that matter?  How are they better off needing to build a new rocket and redo the mission because they failed to complete the contract, versus completing the contract but missing a few extra rep from an optional requirement?  (If they really want that extra rep, sooner or later they can probably just do an extra repeatable contract).

If the main contract has a long enough "testing for stable orbit" time, then if the player really wants the extra rep, they can always terminate the mission before it completes via range safety/destroy from tracking station anyway.
