### ISSUE TITLE
SR rewards are broken

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#16]
I think all this is known, but just getting it all in one place:

- difficult altitude SR reward is too low (possibly by a factor of 10 according to Maxsimal, though that seems big). Baseline is 2 rep, probably taking years to break even.

- intermediate SR reward presumably also too low (something like 1/5 Difficult's?)

- distance SRs offer the same reward (or close enough to get rounded to the same) as difficult altitude; presumably difficult and intermediate should be different, and at least Difficult Distance should be significantly higher than Difficult Altitude (due to larger reqs, and due to needing guidance)

- I'll throw this in too: it's weird that Distance SR and 3Mm both require guidance, but Film SR (which also has a distance component) doesn't. If

**Comment by lpgagnon** [comment]
(left out consideration of cooldown multipliers because of #15)

**Comment by NathanKell** [comment]
Redone.
