### ISSUE TITLE
NRE in GetIntegrationRolloutVariables

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#18]
(from discord, not a new one)

```
[EXC 22:54:41.235] NullReferenceException: Object reference not set to an instance of an object
    KerbalConstructionTime.MathParser.GetIntegrationRolloutVariables (KerbalConstructionTime.BuildListVessel vessel, System.Collections.Generic.List`1[T] mergedVessels) (at <8b3feb21588f436a8367fb8b66b4afc6>:0)
    KerbalConstructionTime.MathParser.ParseIntegrationTimeFormula (KerbalConstructionTime.BuildListVessel vessel, System.Collections.Generic.List`1[T] mergedVessels) (at <8b3feb21588f436a8367fb8b66b4afc6>:0)
    KerbalConstructionTime.BuildListVessel..ctor (ShipConstruct s, System.String ls, System.Double effCost, System.Double bP, System.String flagURL, System.Boolean isHuman) (at <8b3feb21588f436a8367fb8b66b4afc6>:0)
    KerbalConstructionTime.Utilities.RecalculateEditorBuildTime (ShipConstruct ship) (at <8b3feb21588f436a8367fb8b66b4afc6>:0)
    KerbalConstructionTime.KerbalConstructionTime.EditorRecalculation () (at <8b3feb21588f436a8367fb8b66b4afc6>:0)
    UnityEngine.DebugLogHandler:LogException(Exception, Object)
    ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
    UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Seems to be reliably reproducible with this save
[wip.sfs.zip](https://github.com/KSP-RO/ProgramsIssueTracker/files/8981614/wip.sfs.zip)

Load, enter VAB, place a part (e.g. a plain proc structural). Exception starts happening, maybe one per second. Then switching from LC2 to LC1 makes it stop, and switching back doesn't restart it

**Comment by NathanKell** [comment]
I'm not sure how, but Launch Complex 2 has no pads. How did you get rid of its pads?

**Comment by lpgagnon** [comment]
That's a neat trick. It _does_ have a pad, but it's not showing up on initial save load.

initial state:
![Screen Shot 2022-06-25 at 09 37 17](https://user-images.githubusercontent.com/5061230/175775971-0e031043-c005-4931-a59b-c6e6f7d77db1.png)

after clicking >>  and <<
![Screen Shot 2022-06-25 at 09 37 27](https://user-images.githubusercontent.com/5061230/175775973-174bb7cb-b738-45e1-8baf-1572dc30387c.png)


Can't repro in later saves (nor in a save from ~2 weeks earlier), so something specific must have put it in that state, but no idea what.

**Comment by NathanKell** [comment]
Yeah, I don't know either. But to be clear, it *does not have a pad* in the SFS.

Gonna close this unless and until we get a repro. Basically just hoping the gremlins don't return. :D

**Comment by lpgagnon** [comment]
if it doesn't have a pad in the .sfs, how does a pad come into existence with two clicks?

**Comment by lpgagnon** [comment]
better question, where are you looking?
```
					LaunchPads
					{
						KCT_LaunchPad
						{
							level = 0
							fractionalLevel = -0.125
							isOperational = True
							name = Launch Complex 2
							launchSiteName = LaunchPad
							id = f5758b8d-8380-493e-bfe7-9efa2552b90b
							DestructionState
							{
								SpaceCenter/LaunchPad/Facility/Flag
								{
									intact = True
								}
							}
						}
					}
```

**Comment by NathanKell** [comment]
Look for LaunchComplexes. You'll see for the third LaunchComplex (LC-2) there's nothing inside LaunchPads.

A pad gets created because when the save is loaded, for each LC in the file a stub LC is created (with a launch pad) and then it is modified to match the actual LC.

**Comment by NathanKell** [comment]
(however, that pad should later be destroyed so I'm not really sure why it sticks around.)

**Comment by lpgagnon** [comment]
No, I don't see that. I see a launch pad, with the same ID it's had since it got built and still has in my current save

**Comment by NathanKell** [comment]
Huh. I wonder why I thought that last night then. Because yeah, looking at the save again today, it's there.

What's true is that the active Launch Pad index for that complex is -1 (`ActiveLPID = -1`) and that's what's causing the problem. I thought that was a symptom of no pad, but if there's a pad, somehow that got busted.

**Comment by NathanKell** [comment]
Ah. There was a previous issue with dismantling things that might have been a cause for this? Anyway, put in a guard.
