### ISSUE TITLE
Astronaut cost discrepancies

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#19]
I have two pilots (fired the other two). Currently in training for x-1 cockpit.

Alleged per-year astronaut costs (plausible):
![Screen Shot 2022-06-24 at 17 55 42](https://user-images.githubusercontent.com/5061230/175698119-18d5da6c-caba-4304-8e39-95d521406bef.png)

Alleged breakdown, when clicking the (i) button (clearly wrong):
![Screen Shot 2022-06-24 at 17 56 00](https://user-images.githubusercontent.com/5061230/175698120-53e08dd2-613e-428b-8957-5523b59743a3.png)

Astronauts tab, for reference:
![Screen Shot 2022-06-24 at 17 56 16](https://user-images.githubusercontent.com/5061230/175698121-aaff69a0-0939-4980-9b86-9a1883fbd9c0.png)

edit: just realized the breakdown has more data way at the bottom of the window. So the bug is just the two fired astronauts still being listed in the breakdown's list (and wrongly claiming they have upkeep)

**Comment by NathanKell** [comment]
This may have always existed? At any rate, I made no change that would have altered which nauts show up on that tab.

I've fixed the underlying issue however.
