### ISSUE TITLE
Supersonic flight contracts do not have a counter

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ProgramsIssueTracker#2]
The planes programs has a goal of completing 6 supersonic flight contracts, but there seems to be no counter anywhere, either in the program or in the contract text itself, giving you a completion count. Would be ideal to have it in both those locations.

**Comment by dgeastman** [comment]
Edit: I see that the contracts do actually have counter text, it's just kind of buried in the middle of all the text in the same font/color as everything else. Perhaps add blank lines above/below that line, or otherwise make it more obvious. I looked three times and didn't see it....

**Comment by NathanKell** [comment]
Yeah, often contracts with counters have a separate line for that (with whitespace above/below). Seems warranted in this case.

**Comment by pap1723** [comment]
Done
