### ISSUE TITLE
Plane recovery time / caps is busted

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#23]
rocketplane takes 88d to build, capped at 20 engineers

- put rocketplane on runway, recover it immediately: 38d to recover, 20-engineer cap
- put on runway, take off, land back on runway (actually using hyperedit 'land at'), recover: 19d to recover, 15-engineer cap
- put on runway, do a full flight (~6min engine burn), hyperedit back to runway, recover: 29d to recover, 10-engineer cap
- put on runway, do a full flight, splash down, recover: same 29/10 (ruling out a weird side effect of the HE teleport)

Possibly something to do with engine refurb (the more the engine is used, the less it's worth?), but the discrepancies seem too big for that. And in any case, pristine recovery taking 43% of build time is silly

**Comment by lpgagnon** [comment]
data!
immediate recover:
```
progress = 259083.354862276
effectiveCost = 1409.846634
buildPoints = 129541.677431138
integrationPoints = 129541.677431138
cost = 809.846619
integrationCost = 0
mass = 7.0617547
kscDistance = 3417215.75
```
recover after full flight:
```
progress = 163520.7773192212
effectiveCost = 1059.317
buildPoints = 81760.388659610602
integrationPoints = 81760.388659610602
cost = 809.317017
integrationCost = 0
mass = 1.760831
kscDistance = 3336514.25
```

**Comment by lpgagnon** [comment]
After a second flight and recovery (xlr11, total run time ~14min): no change, values stay exactly the same as after first recovery. Possibly because this is indeed refurb-related, and the engine is already considered as used up as it can get after one continuous-rated-time increment

Meanwhile, if I build the same plane _without_ engine, put it on the runway and recovery it right away, I get 20d, cap=15, suggesting it's actually considered _more_ valuable than the plane with fully-used engine. But its progress is much lower at 112,423 (vs 163,520). So there's more going on here than just the BP/cap relationship

**Comment by NathanKell** [comment]
So something is breaking effectiveCost calculation on recovery. Interesting.

**Comment by NathanKell** [comment]
Yes, this is the engine refurb formula at work. It halves the effectiveCost for engines that have run.

The hard cliffs on cap I'm going to fix as part of #22 though.

**Comment by lpgagnon** [comment]
again, I don't believe engine refurb is adequate to explain all the numbers.

> Possibly something to do with engine refurb (the more the engine is used, the less it's worth?), but the discrepancies seem too big for that. And in any case, pristine recovery taking 43% of build time is silly

> Meanwhile, if I build the same plane without engine, put it on the runway and recovery it right away, I get 20d, cap=15, suggesting it's actually considered more valuable than the plane with fully-used engine.

**Comment by NathanKell** [comment]
Update KSCSwitcher. If you haven't, there's a bunch of randomness with recovery because distance is factored in but distance is Very Wrong without the update.

**Comment by lpgagnon** [comment]
with kscswitcher updated, and the staffing updates

1- building plane: 79d/33staff
2- recovering pristine plane from runway: 31d/32 staff
3- recovering plane from runway after a few seconds of burn: 23d/27 staff
4- recovering plane from water just off the runway after a few seconds of burn: 14d/26staff
5- recovering plane from water 300km away after full burn: 20d/19staff

This still seems like nonsense.
- Pristine recovery taking extra-long is just silly, even if it "makes sense" in terms of the refurb formula
- Refurb formula doesn't seem adequate to explain the difference between 3 and 4, nor does a distance factor (a 40% drop in "value" for a few more seconds of burn, but only 4% drop in staffing?)
- 4 vs 5 is maybe explainable by a burn-time-proportional value drop (reflected in 27% staffing drop) combined by a distance penalty; but again it seems silly that the more used up an engine is, the fewer people can work on it

**Comment by RCrockford** [comment]
I'm also getting crazy talk recovery. I have a starter plane that recovers in a few seconds. Junkers cockpit with first XLR11 config. Take off from runway, fly around until fuel exhaustion. Land back at runway. SPH recovery, by the time I have clicked through the crew debrief etc. screens it is recovered.

Seems insanely fast for a rocket plane.

**Comment by ryanc55** [comment]
Some of these issues seem to stem from used engines being assigned lower effective cost for the purpose of refurbishment calculation, and that EC is getting used for the recovery formula.  With a plane that otherwise has very few cost modifiers and a used engine, the EC can actually be lower than the base cost.   

One way to fix that would be to only discount the EC of used engines in the editor scene.  This will make recovery times a bit longer, more toward the #3 case give above by LPG.   But that could be taken care of if needed by modifying the KCT recovery formula.   I'll make a PR for this.

The distance penalty hardcoded into KCT is surprisingly small and linear:  {distance to SC}/.5*body circumference.   There perhaps should be more benefit given to runway landings.

**Comment by ryanc55** [comment]
The effective cost fix as well as a 25% recovery time discount for recovering from a runway are now in the artifact build.

**Comment by NathanKell** [comment]
Closing this again. If there is more weirdness, please open a new issue rather than commenting here.
