### ISSUE TITLE
Make available programs more visible

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#25]
Hide completed programs, bubble availables to the top... something. Having to scroll down the list to even _realize_ you have newly available programs isn't ideal.

An issue my tiny screen encounters faster than the average, but will get annoying for everyone soon enough

Example: if I hadn't already gone looking for its prereqs, I wouldn't have bothered scrolling down to realize Early Lunar Probes is in fact green now.

![Screen Shot 2022-06-26 at 23 31 32](https://user-images.githubusercontent.com/5061230/175855349-a68cb2f0-15fe-422f-bc9f-3aae8c75d210.png)

**Comment by NathanKell** [comment]
They bubble to the top now.

**Comment by ajvaughan** [comment]
Bubbling to the top is not work for me.  
Note I'm no planes, and the x-plane program is at the top, but Early Lunar probes is not.

Is it possible that the code only bubbles one program to the top?

**Comment by NathanKell** [comment]
sfs please? And you completely deleted and replaced your RP-1 folder from the artifacts comment?

**Comment by ajvaughan** [comment]
[ProgramBubbles.zip](https://github.com/KSP-RO/ProgramsIssueTracker/files/8998134/ProgramBubbles.zip)
.sfs attached.  
Note I haven't reloaded since launching my first orbital satellite, so no idea whether it is save/load stable.
And yes I nuked the rp-1 folder and downloaded the new artifact about 8 hours ago.

**Comment by NathanKell** [comment]
Thanks!

**Comment by NathanKell** [comment]
Cannot repro. 
![image](https://user-images.githubusercontent.com/5144098/176125824-9ef6dfa0-cb2f-470c-9c14-1463c1a8a038.png)
