### ISSUE TITLE
No rep for First Polar Satellite

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#29]
It's not _entirely_ useless, unlike First Scientific Satellite; it's a prereq to First Sun Sync, which does offer 50 rep. (and eventually gives access to sun-sync weather sats). But as a non-mandatory-for-program contract, it should offer something, regardless of what ends up happening for mandatories?

**Comment by Teykn** [comment]
If Weathersats and Navsats are going to have their own program (since there currently are unused contracts), I'd advocate for making SSO mandatory alongside any other future rep changes made to mandatory contracts

**Comment by NathanKell** [comment]
Fixed in the rework.
