### ISSUE TITLE
Uncap "Build time at X BP/s" input

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#37]
Currently, manually entering a value in the Integration Info window's input fields seems to ignore any value higher than the rate for the current number of assigned engineers (or plane-size cap if lower?)

That partially breaks my main use for the field: setting it to a standard value (i.e. 1) to determine and compare the "efficiency" of  different LVs.

No more than an inconvenience, but the behavior keeps surprising me

**Comment by siimav** [comment]
It's now possible
