### ISSUE TITLE
proposition: rep normalization (deduction over time)

### ISSUE THREAD

**Issue by Amanthebest4** [KSP-RO/ProgramsIssueTracker#39]
I think rep, if it is in the real sense reputation, should be a consumable. aka, you are consuming your reputation by availing of higher subsidies. also, people tend to forget what you did if you stop doing it. so I suggest a rep loss with the same rep cap system you have. here the rep is normalized to go smack in the middle. the further away from it you get the more you lose/gain. if you are below the middle, natural rep creep to the middle again. aka let's say you had three astronauts die. you are gonna see a drop in rep for a while. but eventually, even with mediocre performance, people will forget.

features of this system:
I think it'll make tuning on rep significantly easier, because it's not a permanent currency.
it'll solve the whole thing you guys were talking about where the best strategy was going towards "take a program and warp". so now to maintain your high subsidies you gotta be launching to maintain and support that. 
and you don't need to be stingy with rewards. cause the rewards lose effectiveness over time, you can afford to give large amounts of rep for big milestones
I also think you should lose rep when you fail objectives. fail objectives in the sense, occurrence of catastrophic failures, such as engine explosions below 70km, collision with fuel on board, astronaut deaths and unconscious events, etc.

P.S. IDK if this is the right place to post this so lemme know.

**Comment by NathanKell** [comment]
Rep decay is in so I'm closing this. Cheers!
