### ISSUE TITLE
CONTRACT_GROUP sort order should mirror Program ordering

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ProgramsIssueTracker#4]

**Comment by pap1723** [comment]
The thing is that it SHOULD already do that. sortKey is set on all of the contract groups in an order that mirrors (or closely mirrors) the order of programs. Unfortunately, that doesn't seem to be working in CC right now.

**Comment by pap1723** [comment]
Fixed by Teykn, apparently 10-20-30-40 it does like, but 11-12-13-14 works properly.
