### ISSUE TITLE
Comm Sat Test vs Comm Sat Early

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProgramsIssueTracker#44]
[both contracts](https://github.com/KSP-RO/RP-0/tree/NotBudgets/GameData/RP-0/Contracts/TO%20BE%20SORTED) give the same 50 rep reward, both have Unlimited repeats, Test is generally much less demanding than Early

Meaning the only reason to do an Early is to unlock even harder contracts

**Comment by NathanKell** [comment]
@pap1723 did this get sorted out?

**Comment by pap1723** [comment]
Yep, this is good to close.
