### ISSUE TITLE
Firing astronauts does not immediately update the budget

### ISSUE THREAD

**Issue by arrowmaster** [KSP-RO/ProgramsIssueTracker#45]
Firing astronauts should immediately cause the budget window to update. It eventually updates on its own but confusing when it doesn't update immediately.

Steps to reproduce:
Start new game
Open budgets window and see that four astronauts cost 10000 per year
Open detailed astronaut budget window to see each astronaut costs 2500 per year
Fire any number of astronauts
Detailed astronaut budget windows will show fewer astronauts but at the bottom the total will still be 10000 per year

**Comment by NathanKell** [comment]
Upkeep listens to all the relevant events now.
