### ISSUE TITLE
No X-Plane option still allows X-Plane Program

### ISSUE THREAD

**Issue by arrowmaster** [KSP-RO/ProgramsIssueTracker#49]
Starting a new game with the No X-Plane RP-1 option still allows the X-Plane program to be selected but no X-Plane contracts will appear.

**Comment by siimav** [comment]
This option just isn't wired up correctly yet. Looks like it will disable contracts but not actually give any rewards boosts.
TBD what we want to do with it. Probably remove entirely?

**Comment by NathanKell** [comment]
Remove the option, yes.

**Comment by NathanKell** [comment]
Removed.
