### ISSUE TITLE
The initial LC creation should open a dialog to confirm/edit choice

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ProgramsIssueTracker#5]
Rather than the 1t/15t choice of starting complex, have either of those open the LC creation dialog with the equivalent starting values, so the player can customize height/width, or pick entirely different values, if so desired. The current hard 1t/15t choice leaves players that want say, a 2t or 3t pad at a disadvantage as they have to edit the pad first.

**Comment by NathanKell** [comment]
It's an interesting suggestion, but I like the current setup for now.
