### ISSUE TITLE
Don't combine required and optional contracts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/ProgramsIssueTracker#56]
@pap1723 when you have time can you separate out the required and optional forms of each contract? It will be much easier for folks to understand (and us to add REQUIREMENT blocks) if they are separate. Cheers!

**Comment by siimav** [comment]
@NovemberOrWhatever I think this is done now?

**Comment by NovemberOrWhatever** [comment]
I think everything optional and repeatable is separate from first ____ contracts. So I'm pretty sure it's done.
