### ISSUE TITLE
Set LC size to a saved vessels #s

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/ProgramsIssueTracker#58]
Allow a player to choose a saved vessel and set the LCs #s to that necessary to build that vessel - rounding up tonnage to the nearest (2 significant digits) and giving a 5% dimension leeway perhaps?

Eg a rocket that masses 245t would round up to 250, a rocket that masses 1534 would round up to 1600.

**Comment by Elouda** [comment]
If done I would definitely suggest giving a fair bit of tonnage overhead also - putting in the middle of the 'acceptable' tonnage range would be ideal, ie for a 245t rocket, a 280t pad (allowing 210-280t rockets iirc) would be ideal.

**Comment by NathanKell** [comment]
Done. Using 10% buffer (and ceil to int) for each value.
