### ISSUE TITLE
Please make a button to open/close the RP-1 window

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/ProgramsIssueTracker#6]
Please add a button, like the one for KCT, that allows opening/closing the RP-1 window in scenes where the toolbar is not present.

**Comment by NathanKell** [comment]
Gonna see if I can just make the applauncher bar show up.

**Comment by lpgagnon** [comment]
Please make this optional (the proposed extra button, the existing kct button, or the applauncher bar).

bonus points for adding blizzytoolbar support to the rp1 button

**Comment by NathanKell** [comment]
Blizzy toolbar support would be pretty cool, PRs gratefully accepted.
