### ISSUE TITLE
Suborbital Research program requirements description

### ISSUE THREAD

**Issue by aeroeng91** [KSP-RO/ProgramsIssueTracker#61]
The requirements for the "X-Plane Research" program explicitly state "Complete contract X-Planes Supersonic at least 6 times". The requirements for the "Suborbital Research" program state "Complete contract Low space film return". This is a bit ambiguous, as it could be understood that all 3 contracts in the "Low space film return" series must be completed, instead of only the 1st contract in the series.

This issue seems to involve only the sounding rocket contracts (SoundingRocketFilm, SoundingRocketBio, SoundingRocketAdvancedBio)  which are series-type contracts ("This is a series of 3 contracts, of which X have been completed").

**Comment by NathanKell** [comment]
Merged.

**Comment by NathanKell** [comment]
Will be addressed in a larger way by #56
