### ISSUE TITLE
Remove construction engineers

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/ProgramsIssueTracker#64]
Per our discussion, having construction engineers seems like it may be negative for the play experience because:

1. It encourages players to pull engineers in/out of LCs more frequently than they should
2. Construction engineers are a separate discipline for rocket engineering, and would generally be external contractors rather than space program staff.

We would replace it w/a speed selector(on the admin building?  On each facility?), that would let a player pick contractors hired/daily expenditure for facilities. 

Additional ideas:
-Admin building level could gate how many hired engineers could be working on a facility, gating facility production rate/maximum facility construction projects
-Max engineers working on a facility should be capped by facility cost, eg: facilities have a minimum construction time.

**Comment by NathanKell** [comment]
Oh yeah this is totally donezo.
