### ISSUE TITLE
Confidence cost stuck at 0

### ISSUE THREAD

**Issue by arrowmaster** [KSP-RO/ProgramsIssueTracker#67]
1. Start new game
2. Quicksave
3. Start a program or two
4. Load quicksave
5. Program confidence cost is now 0 for Normal and Fast
6. Exit to main menu and resume game
7. Program confidence cost is still 0 for Normal and Fast
8. Exit to main menu
9. Start new game
10. Program confidence cost is still 0 for Normal and Fast

**Comment by NathanKell** [comment]
per discord: can't repro, following those steps. Can anyone else?

**Comment by arrowmaster** [comment]
I had to try a few times but I managed to do it again today using the latest zip from last night. Try purchasing a starting program for Fast.

1. Start KSP
2. Start a new game (I did normal)
3. Quicksave
4. Start Early Rocket Dev Fast for 450
5. Start Suborbital Research Slow for 0
6. Open some other screens such as R&D, VAB, Astronaut Complex and return to main menu
7. Accept First flight and Karman line contracts
8. Load Quicksave
9. Start Early Rocket Dev Fast for 0
10. Start Suborbital Research Fast for 0

**Comment by NathanKell** [comment]
Fixed! It's the scene load that does it.
