### ISSUE TITLE
[BUG] Can currently lock yourself out of the Geosat program

### ISSUE THREAD

**Issue by zephyrspace** [KSP-RO/ProgramsIssueTracker#70]
You can lock yourself out the geosat program because the commercial Geostationary Commercial Communications Satellite, has the "Complete 'Commercial Communications Satellite (Early)' contract at least 2 times". This is an optional contract in the Targeted Satellite program which is a pre-req for the Geostationary Program, so if you complete the Targeted Sat program without doing these contracts you can just be stuck with no way forward.

**Comment by NathanKell** [comment]
@Elouda @pap1723 is this still true?

**Comment by NathanKell** [comment]
@Elouda @pap1723 bump?

**Comment by NovemberOrWhatever** [comment]
I fixed the contract requirement. It should be fine now
