### ISSUE TITLE
New LC mass for 1t rockets

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/ProgramsIssueTracker#77]
When you have a rocket slightly below 1t and click New LC, it will offer you a 2t LC, making the rocket not buildable in the LC.
There is also some weirdness with rocket dimensions on upgrades, as you can have fractional dimensions for width/length, but on upgrade it defaults to integers. 
(Also something weird with reported dimensions on  rockets tilted on the pad, but that's a different issue)

**Comment by NathanKell** [comment]
Fixed!
