### ISSUE TITLE
[BUG] EEX Harmony patch not applying

### ISSUE THREAD

**Issue by ZombieZilla** [KSP-RO/ProgramsIssueTracker#78]
Sometime in the last few days, the harmony patch to fix the EEX keybind resetting has stopped functioning. Unsure how to reproduce exactly now, but at least 1 other person has confirmed the bug. This serves mainly as a reminder the bug is present

**Comment by NathanKell** [comment]
I haven't been able to see how this could go wrong, and I haven't been able to make it go wrong, and my settings file has the correct keys in it even after I do all the things that, pre-patch, would make them disappear. So I'm confused, and gonna have to close this until and unless someone has repro for me.
