### ISSUE TITLE
Add tooltip to funds, rep, and science widgets

### ISSUE THREAD

**Issue by siimav** [KSP-RO/ProgramsIssueTracker#8]
TBD what we exactly want to show there.

**Comment by leudaimon** [comment]
It would be good to show the current rep cap on budget

**Comment by NathanKell** [comment]
For science, I'd say show total science ( `KCTGameStates.SciPointsTotal` ) and science for next free applicants ( `Utilities.ScienceForNextApplicants()` )

**Comment by NathanKell** [comment]
Rep and Sci are done. Funds...not so much.

**Comment by NathanKell** [comment]
Oh yeah this is done.
