### ISSUE TITLE
[BUG] Rockets being rolled out can be merged

### ISSUE THREAD

**Issue by TheRealWiwaxia** [KSP-RO/ProgramsIssueTracker#80]
When editing a craft, crafts that are currently being rolled out can be merged. If the merged rocket is trashed it will result in the deletion of the craft being rolled out.

Discord conversation for context.
![Screenshot (14313)](https://user-images.githubusercontent.com/26444769/185834865-8c2644bc-1ff4-4761-bff3-00e0ac2fab84.png)

**Comment by NathanKell** [comment]
Fixed by disabling merging until later.
