### ISSUE TITLE
[Feature Request] show Pop-up when leader retires

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/ProgramsIssueTracker#83]
When a leader retires the player needs to assign a new one. This can currently be missed since there is no pop-up.

Currently all leaders retire after a really long time (30 yrs?), so likely not encountered yet. If some leaders are given shorter times, it will happen more frequently.

**Comment by NathanKell** [comment]
Per discussion in discord, there is a MessageSystem alert when this happens, and it can happen in the midst of, well, anything, so I'm disinclined to show a popup. So I'm going to punt on this pending more testing with leaders (if people are missing retirement notices).
