### ISSUE TITLE
Contract rewards and payout

### ISSUE THREAD

**Issue by Tsits11** [KSP-RO/ProgramsIssueTracker#85]
I strongly feel that the way the contract system works right now- we’re losing money! Simple as that! There’s a number of times I’ve had a contract finished early, only to complete it and lose the funding for the remaining years 😣plus the reputation reward is pathetic, shouldn’t there be a bonus for a quick completion ?

All I’m saying is, should a player finish a contract let’s say2 years early, he should get the remaining money as a one-time instant reward AND THEN move on to other contracts. Any thoughts ?

I’m sorry for posting in the wrong section before !!

**Comment by NathanKell** [comment]
Per discussion in discord, the rep bonus might be too low, but it's very much the point of programs that finishing them early means you forgo the rest of the payout. That's, like, the point of the design.

**Comment by NovemberOrWhatever** [comment]
The rep reward has now been buffed, but the rest of that is intentional. Should be fine now.
