### ISSUE TITLE
LC construction gets duplicated

### ISSUE THREAD

**Issue by fluff-li** [KSP-RO/ProgramsIssueTracker#86]
Either the LC construction upgrade gets duplicated or it must be a visual bug in the Construction-Tabs of RP-1 Budged & Space Center Management.

[Player.log-Pt1.txt](https://github.com/KSP-RO/ProgramsIssueTracker/files/9543075/Player.log-Pt1.txt)
[Player.log-Pt2.txt](https://github.com/KSP-RO/ProgramsIssueTracker/files/9543076/Player.log-Pt2.txt)

![KSP-Programs_double_construction](https://user-images.githubusercontent.com/56023678/189538821-caa62336-e054-4e0b-9200-715ef6e7f72c.png)

**Comment by NathanKell** [comment]
Cannot reproduce. Make sure you are actually up to date with the Programs install.

**Comment by NathanKell** [comment]
Oh crud I apparently had uncommitted code.
