### ISSUE TITLE
Game Printing Duplicate Messages 

### ISSUE THREAD

**Issue by cadlad00** [KSP-RO/ProgramsIssueTracker#89]
I am having an issue with program expiring messages duplicating while programs haven't expired. Causing infinitely duplicating messages breaking save file.

**Comment by NathanKell** [comment]
Sorry, my crystal ball is failing me. Gonna need more to go on than that. Reproduction steps? Save file? Log?

**Comment by cadlad00** [comment]
oh my sorry i thought i was descriptive enough
