### ISSUE TITLE
List the optional contracts associated with a program

### ISSUE THREAD

**Issue by siimav** [KSP-RO/ProgramsIssueTracker#9]

**Comment by ajvaughan** [comment]
Related, so commenting here.

I would like better visibility of contract requirements for contracts that aren't currently offered.  eg contracts that might be unlocked soon in my current programs, and contracts that are in other programs that I am considering accepting.

Details like estimated orbit parameters and payload amounts, to better decide am I ready to do this program.

**Comment by NovemberOrWhatever** [comment]
Is this implemented by Contract Configurator now?

**Comment by siimav** [comment]
> Details like estimated orbit parameters and payload amounts, to better decide am I ready to do this program.

Yeah, this should for the most part work now.

**Comment by NovemberOrWhatever** [comment]
Alright, I guess I can count the CC change as a convincing cause to close this
