### ISSUE TITLE
First Lunar Orbiter & Mapper (Uncrewed) contract still available after completion.

### ISSUE THREAD

**Issue by Pyroden** [KSP-RO/ProgramsIssueTracker#92]
The First Lunar Orbiter & Mapper (Uncrewed) contract shows up along side the repeatable version after completing the original first contract.

**Comment by Falki-git** [comment]
Fixed in https://github.com/KSP-RO/RP-0/pull/1830/commits/ed46ea3b56e3f8256fb406d32545e9009d7bbd5e
