### ISSUE TITLE
Can't finish Program - all milestones done

### ISSUE THREAD

**Issue by mbalazs84** [KSP-RO/ProgramsIssueTracker#93]
I also noticed for the X-Plane contracts that even before I took off the hight milestone was marked done. I'm not sure if it is related or not.

It also might have been my machine, the anti-virus blocked one of the dll-s, had to reinstall the "rp-2 zip" and manually override.
[persistent.zip](https://github.com/KSP-RO/ProgramsIssueTracker/files/9653505/persistent.zip)

Discord note: https://discord.com/channels/319857228905447436/987914369318944788/1024063746190102719

**Comment by siimav** [comment]
The issue can easily be replicated with this save.

However I refuse to dig any deeper into the insane spaghetti code so someone other than me is welcome to investigate this.

**Comment by NathanKell** [comment]
Fixed in https://github.com/KSP-RO/RP-0/commit/2936a0f48894cb8bb426c74fc2d0fe7a33eb6486
