### ISSUE TITLE
Error while loading KCT data

### ISSUE THREAD

**Issue by ghost** [KSP-RO/ProgramsIssueTracker#98]
![screenshot4](https://user-images.githubusercontent.com/110846612/197366328-42b186c8-0570-4f7f-888d-5b035f9f446d.png)

[KSP_log.zip](https://github.com/KSP-RO/ProgramsIssueTracker/files/9845451/KSP_log.zip)

**Comment by siimav** [comment]
Hopefully this particular case will no longer happen
