### ISSUE TITLE
Additional program available for selection when upgrading

### ISSUE THREAD

**Issue by byt3c** [KSP-RO/ProgramsIssueTracker#99]
Even when administrative office is in process of upgrading one can select additional available program.

**Comment by siimav** [comment]
Cannot replicate

**Comment by byt3c** [comment]
I'll try to replicate that with my current playthrough

**Comment by NovemberOrWhatever** [comment]
Alright, this one doesn't seem reproducible at this point. Reopen if you have reproduction steps, but for now I'll close it.
